# Generated by Django 5.0.3 on 2024-03-25 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.JSONField(null=True)),
                ('subcategories', models.JSONField(null=True)),
                ('subproducts', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productId', models.IntegerField(primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('subCategoryId', models.IntegerField(primary_key=True, serialize=False)),
                ('subCategoryName', models.CharField(max_length=100)),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.product')),
            ],
        ),
        migrations.CreateModel(
            name='SubProduct',
            fields=[
                ('subProductId', models.IntegerField(primary_key=True, serialize=False)),
                ('subProductName', models.CharField(max_length=100)),
                ('subCategoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.subcategory')),
            ],
        ),
    ]
